# Generated by Django 5.0.6 on 2024-05-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
