# Generated by Django 5.0.6 on 2024-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('place', models.CharField(choices=[('HTML', 'HTML'), ('DJANGO', 'DJANGO'), ('PYTHON', 'PYTHON'), ('CSS', 'CSS')], default='PYTHON', max_length=100)),
            ],
        ),
    ]
